### ISSUE TITLE
Workbench freezes when a lot of Tabs are opened/closed in sequence

### ISSUE THREAD

**Issue by davemeier82** [SchweizerischeBundesbahnen/scion-workbench#322]
## Describe the bug
When you open and close several workbench tabs in sequence, workbench freezes: Not possible to close or switch tab. Some other buttons are not working. See recording (SBB internal only) https://sbb-my.sharepoint.com/:v:/g/personal/david_meier_sbb_ch/EZBtq3qSpxVNiK9ZzoITVy4BCUEO5abGAXmDv9E335fdkA

## To Reproduce
loop:
 1. open some tabs
 2. close some tabs
suddenly nothing works anymore. The console showed the following errors. But it is unclear if they are related:

main.8a7cf8ed4a659f329034.js:1 ERROR Error: Uncaught (in promise): Error: [PartsLayoutError] No part found in the layout containing the view 'view.2'.
Error: [PartsLayoutError] No part found in the layout containing the view 'view.2'.
    at de._findPartByViewId (main.8a7cf8ed4a659f329034.js:1:618820)
    at de._removeView (main.8a7cf8ed4a659f329034.js:1:616849)
    at de.removeView (main.8a7cf8ed4a659f329034.js:1:613610)
    at main.8a7cf8ed4a659f329034.js:1:625343
    at m.<anonymous> (main.8a7cf8ed4a659f329034.js:1:622742)
    at Generator.next (<anonymous>)
    at main.8a7cf8ed4a659f329034.js:1:1414152
    at new t (polyfills.6212a913a465052eb860.js:1:17790)
    at x (main.8a7cf8ed4a659f329034.js:1:1413848)
    at J._work (main.8a7cf8ed4a659f329034.js:1:622629)
    at V (polyfills.6212a913a465052eb860.js:1:15908)
    at V (polyfills.6212a913a465052eb860.js:1:15444)
    at polyfills.6212a913a465052eb860.js:1:16755
    at T.invokeTask (polyfills.6212a913a465052eb860.js:1:7150)
    at Object.onInvokeTask (main.8a7cf8ed4a659f329034.js:1:240108)
    at T.invokeTask (polyfills.6212a913a465052eb860.js:1:7071)
    at L.runTask (polyfills.6212a913a465052eb860.js:1:2545)
    at M (polyfills.6212a913a465052eb860.js:1:9148)
    at m.invokeTask [as invoke] (polyfills.6212a913a465052eb860.js:1:8231)
    at Z (polyfills.6212a913a465052eb860.js:1:20146)

main.8a7cf8ed4a659f329034.js:1 ERROR TypeError: Cannot read properties of null (reading 'viewId')
    at main.8a7cf8ed4a659f329034.js:1:700257
    at Array.find (<anonymous>)
    at Kl.find (main.8a7cf8ed4a659f329034.js:1:231025)
    at m.onViewDragStart (main.8a7cf8ed4a659f329034.js:1:700224)
    at main.8a7cf8ed4a659f329034.js:1:703377
    at C_ (main.8a7cf8ed4a659f329034.js:1:195361)
    at c (main.8a7cf8ed4a659f329034.js:1:195522)
    at HTMLElement.<anonymous> (main.8a7cf8ed4a659f329034.js:1:362200)
    at T.invokeTask (polyfills.6212a913a465052eb860.js:1:7150)
    at Object.onInvokeTask (main.8a7cf8ed4a659f329034.js:1:240108)

## Expected behavior
Workbench should not freeze

## Screenshots
<img width="938" alt="image" src="https://user-images.githubusercontent.com/16632786/157241493-cee22ab7-3b62-400a-81a9-dd21ae654f69.png">

## Environment
Please complete the following information:

 - https://tms-dev.sbb-cloud.net/
 - Browser: Chrome 99.0.4844.51
 - OS: Windows 10
 - Device: Desktop

**Comment by danielwiehl** [comment]
Thank you, @davemeier82 , for reporting this error. We will try to reproduce the described behavior and fix the problem.

**Comment by k-genov** [comment]
Cannot be reproduced anymore.
